// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2TgmU7L0Xp6WQ6pHS7Mt5GOxR5zfsHHY',
    appId: '1:782844791733:web:5421d2130a635a14d627fc',
    messagingSenderId: '782844791733',
    projectId: 'alarm-cb781',
    authDomain: 'alarm-cb781.firebaseapp.com',
    storageBucket: 'alarm-cb781.firebasestorage.app',
    measurementId: 'G-1BS2L48YN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARF7t-Aw9fPmMCcjfNukWVdkwfaOrp4rM',
    appId: '1:782844791733:android:ddba7c56ede2c22dd627fc',
    messagingSenderId: '782844791733',
    projectId: 'alarm-cb781',
    storageBucket: 'alarm-cb781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfTNWzZkWnwrf51ZPymgVv3K-4NiLnKyw',
    appId: '1:782844791733:ios:351574d329c1558ed627fc',
    messagingSenderId: '782844791733',
    projectId: 'alarm-cb781',
    storageBucket: 'alarm-cb781.firebasestorage.app',
    iosBundleId: 'com.cervus.alarm.alarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfTNWzZkWnwrf51ZPymgVv3K-4NiLnKyw',
    appId: '1:782844791733:ios:351574d329c1558ed627fc',
    messagingSenderId: '782844791733',
    projectId: 'alarm-cb781',
    storageBucket: 'alarm-cb781.firebasestorage.app',
    iosBundleId: 'com.cervus.alarm.alarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2TgmU7L0Xp6WQ6pHS7Mt5GOxR5zfsHHY',
    appId: '1:782844791733:web:96c3a203c2cb2c8bd627fc',
    messagingSenderId: '782844791733',
    projectId: 'alarm-cb781',
    authDomain: 'alarm-cb781.firebaseapp.com',
    storageBucket: 'alarm-cb781.firebasestorage.app',
    measurementId: 'G-X8ECE3XLR0',
  );
}
